import ReduxProvider from "@/components/provider/ReduxProvider";
import SessionProviders from "@/components/provider/SessionProvider";
import Navbar from "@/components/ui/Navbar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProviders>
          <ReduxProvider>
            <Navbar />
            {children}
          </ReduxProvider>
        </SessionProviders>
      </body>
    </html>
  );
}
