export enum RESPONSE_MESSAGE {
  UNAUTHORIZED = 'Unauthorized',
  USER_ALREADY_EXIST = 'user already registered with this email!',
  USER_NOT_FOUND = 'User not found!',
  USER_ALREADY_VERIFYED = 'user email already verifyed!',
  EMAIL_NOT_VERIFYED = 'Email not verifyed! Check your email and verify it',
  SEND_VERIFICATION_EMAIL = 'Verification Email Sended! Chack your email.',
  USER_CREATED_SUCCESSFULL = 'user created succesfull',
  INVALID_EMAIL = 'Invaldi email or password',
  INVALID_PASSWORD = 'Invaldi email or password',
  INTERNAL_SERVER_ERROR = 'Internal Server Error!',
  SERVER_TEMPORARY_DOWN = 'Server is temporary down!',
  INVALID_JWT_TOKEN = 'Invalid Token!',
  JWT_TOKEN_EXPIRED = 'Token is Expired!',
  JWT_TOKEN_REQUIRED = 'Token is Required',
  JWT_BEARER_TOKEN_REQUIRED = 'Bearer token is Required',
  EMAIL_ALREDY_RESIGTARD_ANOTHER_STRATEGY = 'Email alredy registerd another strategy',
  INVALID_CREDENTIALS = 'Invalid credentials',
  TOKEN_IS_BLACKLIST = 'Token is blacklisted!',
}
