export enum ACCOUNT_STATUS {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
  BLOCKED = 'BLOCKED',
  DELETED = 'DELETED',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
}

export enum USER_TYPE {
  USER = 'USER',
  ADMIN = 'ADMIN',
  SUB_ADMIN = 'SUB_ADMIN',
}

export enum SIGNUP_STRATEGY {
  EMAIL = 'EMAIL',
  GOOGLE = 'GOOGLE',
}
